name: Welcome New Contributors

on: 
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for opening your first pull request! 🎉 We appreciate your contribution!'
          pr-message: 'Thanks for submitting your first PR! 🚀 We are excited to review it.'
